# Generated by Django 5.0 on 2024-01-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Myapp", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
